// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZV-DFaXO4175KKDBsHMWhDB3MMeLQls',
    appId: '1:610451573458:web:d3ebf31b6ab7110924bb0b',
    messagingSenderId: '610451573458',
    projectId: 'groupchatapp-5a9d1',
    authDomain: 'groupchatapp-5a9d1.firebaseapp.com',
    storageBucket: 'groupchatapp-5a9d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6QaUki3xT2z9LTNshqyK1bUX5l5q_yQ',
    appId: '1:610451573458:android:9dd50f5287296ffc24bb0b',
    messagingSenderId: '610451573458',
    projectId: 'groupchatapp-5a9d1',
    storageBucket: 'groupchatapp-5a9d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1ahZ8i3Y41c94sK9h7f0em0r-CLhiQk',
    appId: '1:610451573458:ios:85e607f75032857824bb0b',
    messagingSenderId: '610451573458',
    projectId: 'groupchatapp-5a9d1',
    storageBucket: 'groupchatapp-5a9d1.appspot.com',
    iosBundleId: 'com.example.groupChatApp',
  );
}
